---
when:
  - event: push
    branch: main

steps:
  - name: build
    image: oven/bun:1.3.11-alpine
    # language="sh"
    commands:
      - bun install
      - bun run --workspaces build

  - name: deploy
    image: jfxs/wrangler
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_PAGES_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_PAGES_API_TOKEN
    # language="sh"
    commands:
      - wrangler pages deploy app/dist/ --project-name "$${CI_REPO_NAME}"
